apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: dnyani28/sai
          ports:
            - containerPort: 80
